// 1. Strict Enum-like types for status and work type
export type JobStatus = "not_applied" | "in_progress" | "applied" | "completed";
export type JobType = "remote" | "hybrid" | "onsite" | "unknown";

// 2. The Job Interface: Matches your 'jobs' table
export interface Job {
  id: string;             // UUID generated by Supabase
  user_id: string;        // ID of the owner (for Security)
  title: string;
  company: string;
  location: string | null;
  job_type: JobType;
  status: JobStatus;
  url: string;
  notes: string | null;
  created_at: string;
  updated_at: string;
}

// 3. User Profile Interface: Matches your 'profiles' table
export interface UserProfile {
  id: string;
  full_name: string | null;
  avatar_url: string | null;
  created_at: string;
  updated_at: string;
}

// 4. Input types: Used for our Forms (Add/Edit)
// We use Omit because when creating a job, we don't have an ID yet.
export type CreateJobInput = Omit<Job, "id" | "user_id" | "created_at" | "updated_at">;
export type UpdateJobInput = Partial<CreateJobInput>;
